<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>2a367529-10a0-41df-b0b4-fda4335f5049</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.login-btn.btn-territory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='body-wrapper']/app-root/app-login/div/div/div[2]/div/form/div[4]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9fe570b7-0523-49f6-bd24-ec1dbb6e87db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-btn btn-territory</value>
      <webElementGuid>88338b08-82a5-45a1-87ae-9ddab2cb3a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>7896ee73-43c6-45de-99d5-88d62421d898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body-wrapper&quot;)/app-root[1]/app-login[1]/div[@class=&quot;login-wrapper&quot;]/div[@class=&quot;login-content&quot;]/div[@class=&quot;login-spec&quot;]/div[@class=&quot;spec-wrapper&quot;]/form[@class=&quot;login-form-wrap ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;login-btn-wrap&quot;]/button[@class=&quot;login-btn btn-territory&quot;]</value>
      <webElementGuid>77f35de3-e61e-4ec6-834d-8ae6eb02ea82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body-wrapper']/app-root/app-login/div/div/div[2]/div/form/div[4]/button</value>
      <webElementGuid>6aab7c7d-bdc8-4277-af5b-40914b094109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember me'])[1]/following::button[1]</value>
      <webElementGuid>525eb66d-b8e8-4f10-9cdc-3b5ddad131a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>7d67d269-f694-4f2c-b32e-45ed13e083c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>725813b0-ab60-432a-9340-44218b9d8822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>6930e122-bf24-42ed-85cd-02ab82742bad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
